### ISSUE TITLE
Validation of input json string in the main merge method

### ISSUE THREAD

**Issue by syfds** [hemantsonu20/json-merge#14]
The main merge method accepts two json strings (`JsonMerge.merge(srcJsonStr, targetJsonStr);`). There is no input validation for non correct values like null or "" or "    ". For example invocation with `null` produces following error: `java.lang.IllegalArgumentException: argument "content" is null`

I suggest to validate input strings and throw a corresponding exception like `IllegalArgumentException` with a clear error message. 

@hemantsonu20 what do you thing about it?  If it's ok for you, I will create a pull request.

**Comment by hemantsonu20** [comment]
Thanks for your suggestion. So basically I agree with you, we should validate the inputs. In this case inputs are simply delegated to readTree method without any processing, and it's already validating the input, so it will be a duplication at our end. If there were some processing on inputs, then it was necessary to validate the inputs.
