### ISSUE TITLE
Add some complex test cases for this lib

### ISSUE THREAD

**Issue by hemantsonu20** [hemantsonu20/json-merge#4]
A sample test file:
```
[
  {
    "name": "json-merge"
  },
  {
    "age": 18
  },
  {
    "name": "json-merge",
    "age": 18
  }
]
```
Every test file will contain three json objects. First one is the src json, second one is target json, third one is expected output.

So just create some complex test cases in same pattern and define expected output.

Note: Adding just json file in [`test folder`](https://github.com/hemantsonu20/json-merge/blob/master/src/test/resources/json-merge-test) will be picked by junit test. No additonal code is required for running the test case.

**Comment by syfds** [comment]
hi @hemantsonu20, sorry for late response (I'm on vacation now)! I saw that you have already merged the pull request and moved the test file to edge cases, so I have nothing to do.

**Comment by hemantsonu20** [comment]
Yep, nothing to do from your side as of now. Happy vacationing.
